### ISSUE TITLE
Thanks again!

### ISSUE THREAD

**Issue by NCrusher74** [ryanfrancesconi/TaglibWrapper#1]
Thanks again for putting this up for me! I haven't had a chance to fully test it yet, but just so you know, there seems to be a problem with this portion of the wrapper:

```swift
+ (NSString *)detectStreamType:(NSString *)path
{
    const char *filepath = path.UTF8String;
    TagLib::FileStream *stream = new TagLib::FileStream(filepath);

    if (!stream->isOpen()) {
        NSLog(@"Unable to open FileStream: %@", path);
        delete stream;
        return nil;
    }
    const char *value = nil;

    if (TagLib::MPEG::File::isSupported(stream)) {
        value = "mp3";
    } else if (TagLib::MP4::File::isSupported(stream)) {
        value = "m4a";
    } else if (TagLib::RIFF::WAV::File::isSupported(stream)) {
        value = "wav";
    } else if (TagLib::RIFF::AIFF::File::isSupported(stream)) {
        value = "aif";
    }

    delete stream;

    if (value) {
        // NSLog(@"Returning stream file type: %s", value);
        return [NSString stringWithCString:value encoding:NSUTF8StringEncoding];
    }
    return nil;
}
```

Specifically, the `if-else` bits, which all cause this error: "No member named 'isSupported' in 'TagLib::MPEG::File'".

It seems to build okay if I comment out the `if-else` block, but like I said, I haven't had a chance to test it fully. Are you using a different build of TagLib than 1.11.1? I notice your comments list `MOVEMENTNAME` and `MOVEMENTNUMBER` among the tags available, which aren't there in TagLib 1.11.1 (I had to add them manually.)

**Comment by ryanfrancesconi** [comment]
yes, you need to update your taglib for isSupported to be in there. The above is a utility function that's useful, but not necessary for the regular metadata things. I think the current is here:
https://github.com/taglib/taglib

**Comment by NCrusher74** [comment]
Thank you! I had assumed 1.11 was the one most people were using so I hadn't really looked into the 1.12beta on GitHub. Got it!

**Comment by ryanfrancesconi** [comment]
you might not need the detectStreamType functionality, but it was something i did...
