### ISSUE TITLE
Recommend cmake/make commands

### ISSUE THREAD

**Issue by hisaac** [ryanfrancesconi/TaglibWrapper#3]
Thank you for this wrapper! I've been wanting to write something like this myself, but I have very little C++ experience, so it has been a slog.

The readme mentions:

> This implies that you have already built and added the tag.framework to your project.

I understand that building the library requires a couple `cmake` and `make` commands, but I'm not sure which arguments to pass to those commands to make TagLib work with this wrapper. Could you tell me what commands you use?

**Comment by hisaac** [comment]
These are the commands I've been using:

```
cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_FRAMEWORK=ON
make install
```

This does build a tag.framework, but it only includes the header files, not the source files. Maybe I'm missing a command or an argument?

**Comment by hisaac** [comment]
Pinging @NCrusher74 here as well in case you have any insight.

**Comment by NCrusher74** [comment]
Unfortunately, no. I don't actually really understand how to use `cmake` all that much. I just follow the directions and hope it works the way it should when I have to use it.

**Comment by hisaac** [comment]
@NCrusher74  Sounds like we're in the same boat then! 😅 Thanks anyway.

**Comment by NCrusher74** [comment]
If you want to try using my `SPM` version of this wrapper, it already includes the compiled library.

I'm not sure what kind of files you're trying to tag, but if they're `mp3` or `mp4`, I also have Swift libraries I wrote from scratch for that purpose (`TagLib` didn't end up having all the metadata options I was after.)

**Comment by ryanfrancesconi** [comment]
'''
cmake -DCMAKE_BUILD_TYPE=Release \
    -DBUILD_FRAMEWORK=ON \
    -DCMAKE_C_COMPILER=/usr/bin/clang \
    -DCMAKE_CXX_COMPILER=/usr/bin/clang++ \
    -DCMAKE_OSX_SYSROOT=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk \
    -DCMAKE_OSX_DEPLOYMENT_TARGET=10.12 \
    -DCMAKE_OSX_ARCHITECTURES="arm64;x86_64" \
    -DBUILD_SHARED_LIBS=OFF \
    -DCMAKE_INSTALL_PREFIX=/Users/rf/Documents/Dev/ADD-Build/Frameworks/C/taglib-master \
    -DBUILD_EXAMPLES=ON
# make clean
make
./fix_paths.sh
'''

**Comment by hisaac** [comment]
Ah interesting! I don't know much yet about what TagLib does or does not include. What metadata options was TagLib lacking?

**Comment by hisaac** [comment]
Thanks @ryanfrancesconi, I'll give that a try!

**Comment by ryanfrancesconi** [comment]
fix_paths.sh

```

echo "-- Updating paths..."
mv bindings/c/tag_c.framework/Versions/0.0.0 bindings/c/tag_c.framework/Versions/A

# tag
install_name_tool -id \
@loader_path/../Frameworks/tag.framework/Versions/A/tag \
taglib/tag.framework/Versions/A/tag

otool -L taglib/tag.framework/Versions/A/tag

# tag_c
install_name_tool -id \
@loader_path/../Frameworks/tag_c.framework/Versions/A/tag_c \
bindings/c/tag_c.framework/Versions/A/tag_c

install_name_tool -change \
@rpath/tag.framework/Versions/A/tag \
@loader_path/../../Frameworks/tag.framework/Versions/A/tag \
bindings/c/tag_c.framework/Versions/A/tag_c

otool -L bindings/c/tag_c.framework/Versions/A/tag_c
#
echo "-- Moving frameworks..."
rm -fR Frameworks/*
mv taglib/tag.framework Frameworks/tag.framework
mv bindings/c/tag_c.framework Frameworks/tag_c.framework

cd Frameworks/tag_c.framework/Versions
ln -sfn A Current
cd ..
ln -sfn Versions/A/tag_c tag_c
ln -sfn Versions/A/Headers Headers
ln -sfn Versions/A/Resources Resources
```

**Comment by ryanfrancesconi** [comment]
@hisaac that is what i'm using to build tag lib here.

**Comment by NCrusher74** [comment]
> @NCrusher74 Your SwiftTagger libraries look cool! I don't know much yet about what TagLib does or does not include. What metadata options was TagLib lacking?

Thank you. At this point, I'm not sure I remember which tags it was that I wanted that `TagLib` didn't have. It's been several months and several thousand lines of code since I tried implementing it.

There is also, as of the Swift 5.3, I believe, an option for including compiled binaries in Swift Package Manager packages. But I'm not entirely sure how that would work re: `TagLib` but it might be more efficient than my SPM-version of `TagLibWrapper`.

**Comment by ryanfrancesconi** [comment]
One thing to keep in mind in general is that if you want to compile for the new arm64 chips, it's necessary to build with DCMAKE_OSX_ARCHITECTURES="arm64;x86_64" 

I'd say once you have that in there a binary would be safe for a bit. I didn't think that this wrapper is really appropriate to be a package as all the real code is in taglib. This is more an example of an application wrapper for the real framework.

**Comment by ryanfrancesconi** [comment]
Another warning is that taglib as of present is unmaintained. The original author isn't interested...

**Comment by hisaac** [comment]
Thank you both for your help and advice! This is enough for me to continue on with. 🙏
